=== Thekillerjoker/1r-ASIX/Apunts-ASIX/LMSG/XML/smartphones.dtd
<!ELEMENT smartphones (smartphone+)>
<!ATTLIST smartphones any CDATA #REQUIRED>
<!ELEMENT smartphone (marca, model, processador, pantalla, emmagatzematge, connectivitat)>
<!ATTLIST smartphone id CDATA #REQUIRED>
<!ATTLIST smartphone gamma CDATA #REQUIRED>
<!ELEMENT marca (#PCDATA)>
<!ELEMENT model (#PCDATA)>
<!ELEMENT processador (#PCDATA)>
<!ATTLIST processador fabricant CDATA #REQUIRED>
<!ELEMENT pantalla (#PCDATA)>
<!ATTLIST pantalla tipus CDATA #REQUIRED>
<!ATTLIST pantalla mida CDATA #REQUIRED>
<!ATTLIST pantalla unitat CDATA #REQUIRED>
<!ELEMENT emmagatzematge (#PCDATA)>
<!ELEMENT connectivitat (xarxa, wifi, bluetooth?)>
<!ELEMENT xarxa (#PCDATA)>
<!ELEMENT wifi (#PCDATA)>
<!ELEMENT bluetooth (#PCDATA)>
<!ATTLIST bluetooth versio CDATA #REQUIRED>

=== Thekillerjoker/1r-ASIX/Apunts-ASIX/LMSG/XML/smartphones.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE smartphones SYSTEM "smartphones.dtd">
<smartphones any="2025">
    <smartphone id="S01" gamma="alta">
        <marca>Apple</marca>
        <model>iPhone 15 Pro</model>
        <processador fabricant="Apple">A17 Pro</processador>
        <pantalla tipus="OLED" mida="6.1" unitat="polzades" />
        <emmagatzematge>256 GB</emmagatzematge>
        <connectivitat>
            <xarxa>5G</xarxa>
            <wifi>Wi-Fi 6E</wifi>
            <bluetooth versio="5.3" />
        </connectivitat>
    </smartphone>

    <smartphone id="S02" gamma="mitjana">
        <marca>Samsung</marca>
        <model>Galaxy S23 FE</model>
        <processador fabricant="Samsung">Exynos 2200</processador>
        <pantalla tipus="AMOLED" mida="6.4" unitat="polzades" />
        <emmagatzematge>128 GB</emmagatzematge>
        <connectivitat>
            <xarxa>5G</xarxa>
            <wifi>Wi-Fi 6</wifi>
        </connectivitat>
    </smartphone>
</smartphones>
